[package]
name = "pms5003"
version = "0.1.0"
authors = ["David Park <David.Park@agoda.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = ">=1.0", features = ["derive"] }
serde_json = ">=1.0.44"
thruster = { git = "https://github.com/trezm/Thruster.git", features = ["thruster_error_handling"] }
tokio = { version = ">=0.2.6", features = ["fs", "time", "process", "rt-core", "sync", "macros", "io-util"] }
lazy_static = ">=1.4.0"
err-ctx = ">=0.2.3"
async-std = "1.4.0"