version: '2'
services:
  pms5003:
    image: nginx
    labels:
      - "traefik.http.routers.pms5003.rule=Host(`pms5003.pi.local`)"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
